application: gaestarterkit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /cruddy/static
  static_dir: cruddy/static

- url: /static
  static_dir: static

- url: /fonts
  static_dir: static/uikit-2.26.3/fonts

- url: .*
  script: main.app
